ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]
    

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('shop',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('', RedirectView.as_view(pattern_name='shop:allProdCat')),  # Redirect empty path to 'shop/'
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path('',views.SearchResults,name='SearchResults'),
    ]

ecommerceproject/shop/urls.py
from django.urls import path
from .import views

app_name='shop'
urlpatterns = [
    
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),

]

ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    
    def __str__(self):
        return '{}'.format(self.cart_id)
    
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    
    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self) -> str:
        return '{}'.format(self.product)

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
            ordering=('name',)
            verbose_name = ("category")
            verbose_name_plural = ("categories")
    
    def __str__(self):
            return self.name
    
    def get_url(self):
            return reverse("shop:products_by_category",args=[self.slug])
    
class Product(models.Model):
       name=models.CharField(max_length=250,unique=True)
       slug=models.SlugField(max_length=250,unique=True)
       description=models.TextField(blank=True)
       price=models.DecimalField(max_digits=10,decimal_places=2)
       category=models.ForeignKey(Category,on_delete=models.CASCADE)
       image=models.ImageField(upload_to='product',blank=True)
       stock=models.IntegerField()
       available=models.BooleanField(default=True)
       created=models.DateTimeField(auto_now_add=True)
       updated=models.DateTimeField(auto_now=True)

       def get_url(self):
           return reverse("shop:prodCatdetail", args=[self.category.slug,self.slug])
       

       class Meta:
            ordering=('name',)
            verbose_name = ("product")
            verbose_name_plural = ("products")
    
       def __str__(self):
            return self.name
    

ecommerceproject/cart/views.py
from django.shortcuts import get_object_or_404, render,redirect
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity<cart_item.product.stock:
             cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price*cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
     cart=Cart.objects.get(cart_id=_cart_id(request))
     product=get_object_or_404(Product,id=product_id)
     cart_item=CartItem.objects.get(product=product,cart=cart)
     cart_item.delete()
     return redirect('cart:cart_detail')

ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def SearchResults(request):
    product=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        product=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'product':product})

ecommerceproject/shop/views.py
from django.shortcuts import get_object_or_404, render,HttpResponse
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})


def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerceproject/templates/base.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/cutom.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://db.onlinewebfonts.com/c/8cdbb48678e4418f22a2f507c2b975bd?family=Blanka-Regular" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <meta name="descripton" content="{% block metadescripton %}{%endblock%}">
    <script src="https://kit.fontawesome.com/916fdde311.js" crossorigin="anonymous"></script>
    <title>{% block title %}{%endblock%}</title>
    
</head>
<body style="background-color: #f4f4f4;"><div>
    {%include 'header.html'%}
    {%include 'navbar.html'%}
    {% block content%}
    {%endblock%}
    </div>
    {%include 'footer.html'%}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    This is Cart Page. proceed to review items and place order

{% endblock  %}
{% block title  %}
Cart Tech Mart pvt ltd
{% endblock  %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your cart is empty</h1>
        <br>
        <p class="text-center">Please click <a href="{% url 'shop:allProdCat'%}"> here </a> to continue shopping</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping Cart</h1>
        <br>
    </div>
</div>
<div class="container-fluid">
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table ">
            <thead >
                <tr>
                    <th class="my_custom_thead rounded-top" colspan="5">Your Items</th>

                </tr>

            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" height="125px" width="125px"></a>

                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        PRICE:Rs {{cart_item.product.price}}
                        <br>
                        Quantity:{{cart_item.quantity}} x {{cart_item}}

                    </td>
                    <td>
                        Rs {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-plus custom_icon"></i></a>
                        &nbsp;
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        
                        &nbsp;
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                        &nbsp;
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div class="mx-auto">
        <table class="table my_custom_table">
            <thead >
                <tr>
                    <th class="my_custom_thead rounded-top">
                        Check Out
                    </th>
                </tr>
            </thead>
            <tbody >
                <tr>
                    <td >
                        Please review your shopping cart items before proceeding with order payment.
                    </td>
                    
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total :<strong>Rs{{total}}</strong>

                    </td>
                </tr>
                <tr>
                    <td >
                        <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button" >continue shopping</a>
        </div>
                    </td>
                </tr>

            </tbody>
            
        </table>
        
            
    </div>
    {% endif %}
</div>


{% endblock  %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{category.description|truncatewords:155}}
{% else %}
     Welcome to Abc store where you can buy different items
{% endif %}
{% endblock  %}
{% block title  %}
{% if category %}
    {{category.name}}-Abc store
{% else %}
     See our new items
{% endif %}
{% endblock  %}
{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class" style="background-color: aliceblue;">
            <div class="mx-auto">
            <p class="px-3  py-2 my_title"><a href="{% url 'shop:allProdCat' %}">Our Product collection</a></p>
        </div>
    </div>
    </div>
{% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
 {%else%}
 <div class="mx-auto">
 <img class="my_image my_image_height" src="{% static 'img/bannerr.png'%}"  alt="our products">
</div>
<br>
<div style="border: 1px;">
    <h1 class="text-center my_title">our products collection</h1>
    <p class="text-center disc">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque tempore illo officiis explicabo, adipisci tenetur architecto ipsam praesentium suscipit nam facere deserunt. Eaque nobis est, vel possimus aspernatur saepe quos!</p>
</div>
 {% endif %}
 <div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list  %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="main-container">
                <div class="cards">
                    <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <h3 class="product-name">{{product.name}}</h3>
                    
                    <p class="product-detail">{{product.category}}</p>
                    <p class="product-cost">Rs{{product.price}}</p>
                    <div class="buy-btn"><a  style="text-decoration:none; color: whitesmoke;" href="{{product.get_url}}">Buy Now</a></div>
                </div>
             </div>
           
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
              <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {%endif%}">{{pg}}</a>
              {% endfor %}
            </div>
        {% endif %}
    </div>
    <br>
 </div>

{% endblock  %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;Abc tech pvt ltd. all rights reserved</p>
</div>

ecommerceproject/templates/header.html
 {% load static %}
 <header class="logobg">
    <center>
       <a href="{% url 'shop:allProdCat' %}"> <img class="logoimaget" src="{% static 'img/logo.png'%}" alt="logoimage"></a>
    </center>
 </header>

ecommerceproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-black navbar-dark py-2 ">
    <div class="container-fluid ">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
            <a href="{% url 'shop:allProdCat' %}"> <img src="{% static 'img/tech.png'%}"  alt="logoimage"></a>
         
          </a>
          
          <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
            </a>
            <ul class="dropdown-menu bg-dark" >
              <li><a class="dropdown-item " style="color: whitesmoke;"  href="{% url 'shop:allProdCat' %}"onMouseOver="this.style.color='black'"
                onMouseOut="this.style.color='whitesmoke'">All Produts</a></li>
              {% for cat in links  %}
              <li><a class="dropdown-item " style="color: whitesmoke;" href="{{cat.get_url}}" onMouseOver="this.style.color='black'"
                onMouseOut="this.style.color='whitesmoke'">{{cat.name}}</a></li>
              {% endfor %}
              
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link"href="{% url 'cart:cart_detail' %}" ><i class="fa-solid fa-cart-shopping fa-xl"></i><sup >{{item_count}}</sup></a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" role="search" action="{% url 'search_app:SearchResults' %}" method='get'>
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
        
      </div>
    </div>
    
  </nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:155}}

{% endblock  %}
{% block title  %}

    {{product.name}}-Abc store


{% endblock  %}
{% block content %}
<div class="row my_prod_row_class" style="background-color: aliceblue;">
    <div class="mx_auto">
        <p class="px-3 my_title"><a href="{% url 'shop:allProdCat'%}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    
    </div>
</div>


<div class="container">
<div class="containers">
    <div class="imgBx">
        <img class="product_img img" src="{{product.image.url}}" alt="{{product.name}}" width="400px" height="600px">
    </div>
    <div class="details">
        <div class="content">
            <h2>{{product.name}} <br>
                <span>{{product.category}}</span>
            </h2>
            <p>
                {{product.description}}
            </p>
            
            <h3>Rs. {{product.price}}</h3>

            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text my_custom_a"><b>out of stock</b></p>
            {%else%}
            <p class="my_custom_a"><a class="btn " href="{% url 'cart:add_cart' product.id %}"><b>Add to cart</b></a></p>
            {% endif %}
            
        
        </div>
    </div>
</div>
</div>


{%endblock%}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     We have variety of products.

{% endblock  %}
{% block title  %}
Search
{% endblock  %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in product %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>${{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">No results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock  %}